### ISSUE TITLE
is it possible to integrate serialnumber decoding?

### ISSUE THREAD

**Issue by Mart-Muc** [spacemanspiff2007/SmlLib#13]
wäre es für dich möglich, ein decodierung der hex seriennummer in decimal einzufügen?

Zitat (https://tasmota.github.io/docs/Smart-Meter-Interface/):
If you want you can also convert it to your Identifikationsnummer with some ASCII, DEC and HEX encoding. 0A-01-45-46-52-ST-UV-WX-YZ = 1EFR + string(S) + string(T) + hexToDec(UVWXYZ)

Danke, Mart

**Comment by spacemanspiff2007** [comment]
I don't understand what your goal is and your link doesn't provide any insight.
Does this only work with a specific energy meter?

**Comment by ixs** [comment]
@spacemanspiff2007 I suspect that issue can be closed. If I understand correctly, op is trying to get his Tasmota device to display data from his metering device.

He probably stumbled to your library as I use it in https://github.com/ixs/tasmota-sml-parser to help people build their Tasmota config files for their meters.

https://github.com/ixs/tasmota-sml-parser/issues/1 looked very related to your issue.

**Comment by spacemanspiff2007** [comment]
Thank you for your feedback!
