### ISSUE TITLE
Still open: InvalidBufferPos: Start pos bigger than buffer

### ISSUE THREAD

**Issue by EckhardM** [spacemanspiff2007/SmlLib#15]
Even in version 1.2 I get the following error: 
 `File "/opt/daemon/ehz-daemon5.py", line 78, in <module>
    obis_values = sml_frame.get_obis()
  File "/usr/local/lib/python3.9/dist-packages/smllib/sml_frame.py", line 123, in get_obis
    self._parse_msg(data)
  File "/usr/local/lib/python3.9/dist-packages/smllib/sml_frame.py", line 108, in _parse_msg
    _lst[i] = v = self.get_value()
  File "/usr/local/lib/python3.9/dist-packages/smllib/sml_frame.py", line 27, in get_value
    raise InvalidBufferPos(f'Start pos bigger than buffer: {pos} > {self.buf_len}')
smllib.errors.InvalidBufferPos: Start pos bigger than buffer: 244 > 244`

`

**Comment by spacemanspiff2007** [comment]
Could you provide the raw frame data so I can reproduce the issue?

**Comment by EckhardM** [comment]
Unfortunately not yet. It was running for many week without any error (every 2 seconds). I will enable the logging now so I will have the failing frame next time.

**Comment by spacemanspiff2007** [comment]
Could you fall back to ``parse_frame()`` when ``get_obis()`` fails?
This seems to be one of the rare messages where the shortcut doesn't work.

**Comment by EckhardM** [comment]
I currently catch the exception (with `try/except`) and ignore the problem frame. I will also try to investigate why a few frames are not working.

**Comment by spacemanspiff2007** [comment]
You don't have to ignore the frame, use `parse_frame()` to get the values.
`get_obis()` is a shortcut which works most of the time but in rare cases it doesn't and it seems you are hitting those.

**Comment by spacemanspiff2007** [comment]
I've modified the readme
