### ISSUE TITLE
Negative current consumption; no feed-in

### ISSUE THREAD

**Issue by HWiese1980** [spacemanspiff2007/SmlLib#3]
Hey, it's me again. 

The sml2mqtt service I'm running on my Raspi Zero W works now, but I've noticed one thing I feel is still off. The service reports negative consumption values (aktuelle Wirkleistung; I suppose you're from Germany, like me?) even though I've got no feed-in (Einspeisung) and the smart meter shows the correct (positive) value on its display. 

I'm not sure but it seems like the scaler isn't evaluated under some circumstances. The reported value multiplied by the given scaler gives a much more realistic consumption (close to what the Smart Meter shows on its display; I'm unfortunately not fast enough to check all three values simultaneously to be sure).

It might also be a faulty smart meter firmware as described here: https://wiki.volkszaehler.org/hardware/channels/meters/power/edl-ehz/dzg_dvs74 (the second yellow box).

If you want to check, here's the message I'm getting:

```
b'76051b105102620062007263010176010102310b0a01445a47000282c0b0726201650548bbeb62026339c20076051c105102620062007263070177010b0a01445a47000282c0b0070100620affff726201650548bbeb7577070100603201010172620162006200520004445a470177070100600100ff017262016200620052000b0a01445a47000282c0b00177070100010800ff641c01047262016200621e52ff650800a9e40177070100020800ff017262016200621e52ff62000177070100100700ff017262016200621b52fe53aefe010101638c670076051d1051026200620072630201710163e39a00'
```

**Comment by HWiese1980** [comment]
Here's the log excerpt of the corresponding message with the negative consumption value

```
[2021-08-24 11:20:22,988] [sml.device.ttyUSB0     ] INFO     |             <SmlListEntry>
[2021-08-24 11:20:22,995] [sml.device.ttyUSB0     ] INFO     |                 obis           : 0100100700ff
[2021-08-24 11:20:23,002] [sml.device.ttyUSB0     ] INFO     |                 status         : None
[2021-08-24 11:20:23,010] [sml.device.ttyUSB0     ] INFO     |                 val_time       : 0
[2021-08-24 11:20:23,016] [sml.device.ttyUSB0     ] INFO     |                 unit           : 27
[2021-08-24 11:20:23,023] [sml.device.ttyUSB0     ] INFO     |                 scaler         : -2
[2021-08-24 11:20:23,031] [sml.device.ttyUSB0     ] INFO     |                 value          : -20738
[2021-08-24 11:20:23,042] [sml.device.ttyUSB0     ] INFO     |                 value_signature: None
[2021-08-24 11:20:23,054] [sml.device.ttyUSB0     ] INFO     |                 -> -207.38W (aktuelle Wirkleistung)
```

**Comment by spacemanspiff2007** [comment]
Thanks for the link - it really looks like the buggy firmware.

```
77070100100700ff017262016200621b52fe53aefe010101638c6
                                    ^^^^^^
```

``AEF0`` is 44798 unsigned or -20738 signed.

**Comment by HWiese1980** [comment]
True. I'm wondering if there's something I can *actively* do about it or if it's something that has to be corrected in the `SmlLib` or the `sml2mqtt`.

**Comment by spacemanspiff2007** [comment]
The easiest way would be to locally edit the sml_device.py in your venv/sml2mqtt folder and add the following at line 94:

```python
                if name == '0100100700ff':
                    sml_obj.value = int.from_bytes(sml_obj.value.to_bytes(2, byteorder='big', signed=True), byteorder='big', signed=False)
```

**Comment by HWiese1980** [comment]
Yeah, I'd totally be fine with a quick fix for now. I'll give it a try. Thank you! 

Maybe I can find the time to dig deeper into the code and at some point come up with some customizable workaround strategy (or even a PR). But I can totally feel your situation. Priorities, others they are. ;-)

**Comment by HWiese1980** [comment]
Just to report back: the workaround works as expected. I'm receiving realistic consumption values now. 

Thank you!

**Comment by HWiese1980** [comment]
One more thing to add: I've had cases where the workaround mentioned in https://github.com/spacemanspiff2007/SmlLib/issues/3#issuecomment-904590057 crashed because the resulting value was too big. I added `and sml_obj.value < 0` to the condition. Now it works for me without issues.
