### ISSUE TITLE
OBIS Codes

### ISSUE THREAD

**Issue by Froschie** [spacemanspiff2007/SmlLib#6]
Hello,

Great SML module for python. I´ll be using it soon for one of my scripts.

One improvement I´ve added in my script is to decoded the OBIX Hex strings you output.

https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PmDrivers/IEC62056_OBIS.htm
If looking at the whole HEX string is contains: A-B:C.D.E*F

Personally I think C.D.E is sufficient.

In my testing today simply decoded it with:
obis_C = int(value[4:6], 16)
obis_D = int(value[6:8], 16)
obis_E = int(value[8:10], 16)
obis_string = "{}.{}.{}".format(obis_C, obis_D, obis_E)

Would be great if your library would decode it directly instead of giving the RAW Hex value.

Thanks.

**Comment by niksauer** [comment]
I've created the following utilities to deal with OBIS codes:

```python
import re
from typing import List

OBIS_CODE_REGEX = r'^\d+-\d+:\d+.\d+.\d+\*\d+$'  # Format: A-B:C.D.E*F
OBIS_HEX_REGEX = r'^[\da-fA-F]{12}$'  # Format: twelve hex digits


def is_obis_code(str: str) -> bool:
    return bool(re.match(OBIS_CODE_REGEX, str))


def is_obis_hex(str: str) -> bool:
    return bool(re.match(OBIS_HEX_REGEX, str))


def obis_code_to_hex(obis: str) -> str:
    if not is_obis_code(obis):
        raise ValueError('Input does not represent a valid OBIS code')

    groups: List[str] = re.split(r'\D+', obis)
    return ''.join(['{:02x}'.format(int(group)) for group in groups])


def _obis_hex_to_groups(hex: str) -> List[int]:
    if not is_obis_hex(hex):
        raise ValueError('Input does not represent a valid OBIS hex')

    return [int(hex[i:i + 2], 16) for i in range(0, len(hex), 2)]


def obis_hex_to_code(hex: str, short: bool = False) -> str:
    groups = _obis_hex_to_groups(hex)

    if short:
        return '{0}.{1}.{2}'.format(*groups[2:-1])

    return '{0}-{1}:{2}.{3}.{4}*{5}'.format(*groups)

```

Feel free to include them in this library. This project has helped me a lot 🙂
